<?xml version="1.0"?>
<!--
Gerçek Robot URDF - Teknofest Diffbot
Özellikler:
- Base: 0.60m x 0.55m x 0.24m
- Wheel radius: 0.055m
- Differential drive with caster wheel
- LIDAR mounted on top

NOT: ros2_control entegrasyonu YOK (Micro-ROS kullanıyoruz)
-->
<robot name="my_robot" xmlns:xacro="http://www.ros.org/wiki/xacro">

  <!-- Import materials -->
  <xacro:include filename="$(find my_robot_description)/urdf/my_robot.materials.xacro" />

  <!-- Robot ölçüleri (Gerçek robot ölçüleri) -->
  <xacro:property name="PI" value="3.1415926535897931"/>
  <xacro:property name="base_width" value="0.55" />
  <xacro:property name="base_length" value="0.60" />
  <xacro:property name="base_height" value="0.24" />
  <xacro:property name="wheel_len" value="0.030" />
  <xacro:property name="wheel_radius" value="0.055" />
  <xacro:property name="caster_wheel_radius" value="0.055" />
  <xacro:property name="axle_offset" value="0.10" /> 

  <!-- Root frame -->
  <link name="base_footprint" />

  <!-- Gövde (base_link) -->
  <link name="base_link">
    <collision>
      <origin xyz="${base_length/2 - axle_offset} 0 ${base_height/2}" rpy="0 0 0"/>
      <geometry>
        <box size="${base_length} ${base_width} ${base_height}"/>
      </geometry>
    </collision>

    <visual>
      <origin xyz="${base_length/2 - axle_offset} 0 ${base_height/2}" rpy="0 0 0"/>
      <geometry>
        <box size="${base_length} ${base_width} ${base_height}"/>
      </geometry>
      <material name="orange"/>
    </visual>

    <inertial>
      <mass value="5.0"/>
      <origin xyz="${base_length/2 - axle_offset} 0 ${base_height/2}"/>
      <inertia 
        ixx="0.10" ixy="0" ixz="0" 
        iyy="0.10" iyz="0" 
        izz="0.10"/>
    </inertial>
  </link>

  <!-- base_footprint -> base_link joint -->
  <joint name="base_joint" type="fixed">
    <parent link="base_footprint"/>
    <child link="base_link"/>
    <origin xyz="0 0 0" rpy="0 0 0"/>  
  </joint>

  <!-- LIDAR -->
  <xacro:property name="laser_radius" value="0.05"/>
  <xacro:property name="laser_length" value="0.045"/>
  <xacro:property name="laser_origin_z" value="${base_height * 1.1}"/>

  <joint name="base_link_to_laser" type="fixed">
    <parent link="base_link"/>
    <child link="laser_link"/>
    <origin xyz="${base_length/2 - axle_offset} 0 ${laser_origin_z}" rpy="0 0 0"/>
  </joint>

  <link name="laser_link">
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <cylinder radius="${laser_radius}" length="${laser_length}"/>
      </geometry>
      <material name="black"/>
    </visual>
    <collision>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <cylinder radius="${laser_radius}" length="${laser_length}"/>
      </geometry>
    </collision>
    <inertial>
      <mass value="0.1"/>
      <origin xyz="0 0 0"/>
      <inertia 
        ixx="0.001" ixy="0" ixz="0" 
        iyy="0.001" iyz="0" 
        izz="0.001"/>
    </inertial>
  </link> 

  <!-- Sol Teker -->
  <joint name="left_wheel_joint" type="continuous">
    <parent link="base_link"/>
    <child link="left_wheel"/>
    <origin xyz="0 ${base_width/2} 0" rpy="0 0 0"/>
    <axis xyz="0 1 0"/>
    <dynamics damping="0.2"/>
  </joint>

  <link name="left_wheel">
    <collision>
      <origin xyz="0 0 0" rpy="${PI/2} 0 0"/>
      <geometry>
        <cylinder length="${wheel_len}" radius="${wheel_radius}"/>
      </geometry>
    </collision>
    <visual>
      <origin xyz="0 0 0" rpy="${PI/2} 0 0"/>
      <geometry>
        <cylinder length="${wheel_len}" radius="${wheel_radius}"/>
      </geometry>
      <material name="black"/>
    </visual>
    <inertial>
      <mass value="1.0"/>
      <origin xyz="0 0 0"/>
      <inertia 
        ixx="0.01" ixy="0" ixz="0" 
        iyy="0.01" iyz="0" 
        izz="0.01"/>
    </inertial>
  </link>

  <!-- Sağ Teker -->
  <joint name="right_wheel_joint" type="continuous">
    <parent link="base_link"/>
    <child link="right_wheel"/>
    <origin xyz="0 -${base_width/2} 0" rpy="0 0 0"/>
    <axis xyz="0 1 0"/>
    <dynamics damping="0.2"/>
  </joint>

  <link name="right_wheel">
    <collision>
      <origin xyz="0 0 0" rpy="${PI/2} 0 0"/>
      <geometry>
        <cylinder length="${wheel_len}" radius="${wheel_radius}"/>
      </geometry>
    </collision>
    <visual>
      <origin xyz="0 0 0" rpy="${PI/2} 0 0"/>
      <geometry>
        <cylinder length="${wheel_len}" radius="${wheel_radius}"/>
      </geometry>
      <material name="black"/>
    </visual>
    <inertial>
      <mass value="1.0"/>
      <origin xyz="0 0 0"/>
      <inertia 
        ixx="0.01" ixy="0" ixz="0" 
        iyy="0.01" iyz="0" 
        izz="0.01"/>
    </inertial>
  </link>

  <!-- Ön Caster Teker -->
  <joint name="caster_frontal_wheel_joint" type="fixed">
    <parent link="base_link"/>
    <child link="caster_frontal_wheel"/>
    <origin xyz="${base_length - axle_offset - caster_wheel_radius} 0 ${-wheel_radius + caster_wheel_radius}" rpy="0 0 0"/>
  </joint>

  <link name="caster_frontal_wheel">
    <collision>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <sphere radius="${caster_wheel_radius}"/>
      </geometry>
    </collision>
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <sphere radius="${caster_wheel_radius}"/>
      </geometry>
      <material name="white"/>
    </visual>
    <inertial>
      <mass value="0.3"/>
      <origin xyz="0 0 0"/>
      <inertia 
        ixx="0.001" ixy="0" ixz="0" 
        iyy="0.001" iyz="0" 
        izz="0.001"/>
    </inertial>
  </link>

</robot>
